{
 "title": "PriceStream Dashboard",
 "panels": [
  {
   "title": "Total Crypto Records Stored",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pricestream_records_stored_total"
    }
   ]
  },
  {
   "title": "Background Fetch Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pricestream_fetch_success_total[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(pricestream_fetch_empty_total[1m])",
     "legendFormat": "Empty"
    }
   ]
  },
  {
   "title": "API Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri, status) (rate(http_server_requests_seconds_count{uri!~\".*actuator.*\"}[1m]))",
     "legendFormat": "{{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "API Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (uri) (rate(http_server_requests_seconds_sum{uri!~\".*actuator.*\"}[1m])) / sum by (uri) (rate(http_server_requests_seconds_count{uri!~\".*actuator.*\"}[1m]))) * 1000",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}